title: <p align="center">Junyoung Im </p>

logo: "/images/mypic-modified_2.png?raw=true"

description: >
  <p align="center">
  <a href="https://drive.google.com/file/d/1sYPRcFIFQirfRr30ISkFY28Zup-n1B1E/view?usp=sharing">Resume</a>
  </p>
  
  <p align="justify">
  I am currently a third-year student pursuing bachelor's degree in Enviornment and Information Studies at Keio University.
  <br><br>
  My current interest is in machine learning and augmented reality. I have taken basic computer science classes and am associated in Takeda Lab (Generative AI). 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
